### ISSUE TITLE
[TypeError] builtin typeConverter int takes [...], int provided

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#14]
https://github.com/adsharma/py2many/blob/main/tests/expected/binit.py fails with a curious error:

> [TypeError] builtin typeConverter int takes [<class 'float'>, <class 'str'>, <class 'bool'>], <class 'int'> provided
> 7>16:

**Comment by Coronon** [comment]
Already seen this, should be on my roadmap, I think thats where you do `int(len(…))`

**Comment by Coronon** [comment]
This was actually just a bug in `int` as it seems I forgot to whitelist int´s ^^

Fixed in: abeba60f5552d3f2f1a064ab3489d48df7f70ff4
