### ISSUE TITLE
ast.While

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#15]
https://github.com/adsharma/py2many/blob/main/tests/cases/binit.py now fails on ast.While.

**Comment by Coronon** [comment]
While loops: c5023a051e81981f01343b3e2c2b03e6507e04af
Fixed bug that would not allow function return as index: 46d921bce0f6e8e5e110518e241460cbc0f2d1e5

The provided test is now fully supported (and succeeds)

PS: Please note that you should avoid `while True:` as the keywoards `break` and `continue` are not implemented (and probably never will be -> Racket)
