### ISSUE TITLE
Assert, Dict, IfExp, Pass, Set

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#2]
I am running transpyle on the test cases in https://github.com/adsharma/py2many/tree/main/tests/cases, and many of the simpler cases fail transpiling  because the following ast are not implemented Assert, Dict, IfExp, Pass, Set

**Comment by Coronon** [comment]
Yes, indeed, a lot of ast nodes are not implemented. You should not however rely on `assert` as this is a sole debug feature in Python. `If` `else` and `elif` should however work out of the box. Did you try to use Python3.8? There were large changes to the AST in Python9.

**Comment by jayvdb** [comment]
Ya, I saw that part of the readme and was using Python 3.8.  We are only using `assert` in the test cases.  `IfExp` is `a = 'foo' if 1 else 'bar`.

**Comment by Coronon** [comment]
I see, it’s probably not implemented because I didn’t need it for the ‘easy’ school assignments. This would however require another ‘lightweight’ implementation of if-scopes as these can be nested. I’ll have a look into it.

**Comment by Coronon** [comment]
This is now supported :)
