### ISSUE TITLE
Assert

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#5]
Spawning from #2, `assert ..` is not supported.  This is a critical component of the black-box testing that py2many test cases use, comparing the output of python programs with the output of transpiled programs.

I assume https://rosettacode.org/wiki/Assertions#Racket - second option is what we would need. (and `"a is not 42"` should be `"x is not 42"` on that page.

**Comment by Coronon** [comment]
Added in 0f76265

**Comment by jayvdb** [comment]
py2many test case `assert.py` passes except for stdout differences mentioned at the end of https://github.com/Coronon/PySchemeTranspiler/issues/7.
```diff
- [b'OK']
+ [b'OK ']
```

**Comment by Coronon** [comment]
Fixed in 70c001c
