### ISSUE TITLE
Support implicit returns

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#6]
I edited [`print.py`](https://github.com/adsharma/py2many/blob/main/tests/cases/print.py) to add a `return` so it becomes
```py
def show():
    print('b')
    print(2, 'b')
    a: float = 2.1
    print(a)
    b = 2.1
    print(b)
    c = True
    print('True' if c else 'False')
    return


if True:  # This bit is transformed with my wrapper
    show()
```

Then I get

```
[ValueError] Node of type '<class 'NoneType'>' is not fully supported
[AttributeError] 'NoneType' object has no attribute 'lineno'
10>4:  return
```

This is fixed by changing it to `return None`.

It would be nice if this requirement to add `return None` was removed.

**Comment by Coronon** [comment]
I have implemented this now. Would you prefer the explicit `return` or an automatic implicit version (no `return` -> `return None` implied)? The implicit one can cause a not so informative warning when a function is annotated with a return type other than `None` without an explicit return.

#### With explicit return:
```py
def show() -> int:
    if True:
        print("Hi")
    return
```
->
```
[TypeWarning] Can not assure type correctness for None
6>4:  return
```

#### Without explicit return:
```py
def show() -> int:
    if True:
        print("Hi")
```
->
```
[TypeWarning] Can not assure type correctness for None
3>0:  def show() -> int:
```

**Comment by jayvdb** [comment]
I would prefer no `return.*` needed, and a bare "return" should be acceptable.

A warning is a great idea, for when the return types do not match the function annotation, but it shouldnt error, as there are better tools that people can use for that (mypy).

**Comment by Coronon** [comment]
Added in 6374c41

A little note:
There is a difference between:
```py
def f():
    ...
```
and
```py
def f() -> None:
    ...
```

The former allows returning of arbitrary types which can then be "cast" like this:
```py
# This could fail at runtime (user takes the risk when not annotating the function)
var: int = f() # int or any other type name

# You could also
var = f()
var2: int = f()
```
while the later does not (protects from type runtime exceptions).
