### ISSUE TITLE
`ast.In` is not fully supported, in if-expressions

### ISSUE THREAD

**Issue by jayvdb** [Coronon/PySchemeTranspiler#8]
https://github.com/adsharma/py2many/blob/main/tests/cases/global.py is internally converted into a more typed Python:
```py
code_0: int = 0
code_1: int = 1
l_a: List[int] = [code_0, code_1]
code_a: str = 'a'
code_b: str = 'b'
l_b: List[str] = [code_a, code_b]
if True:
    for i in l_a:
        print(i)
    for i in l_b:
        print(i)
    if 'a' in ['a', 'b']:
        print('OK')
```
which fails at
```
[ValueError] Node of type '<class '_ast.In'>' is not fully supported
[AttributeError] 'In' object has no attribute 'lineno'
12>7:  for i in l_a:
```

**Comment by Coronon** [comment]
The `in` keyword is actually fully supported in for-loops as it is not a seperate token. The error you got is caused by the `if ‘a’ in [‘a’, ‘b’]` as the `in` is its own keyword and token here. This operation is not supported yet but on my roadmap.

**Comment by Coronon** [comment]
Oh and also you can not reuse `i` as in `for i in ...:` like this as one of those is of type **int**, while the other would be a **str**.

**Comment by jayvdb** [comment]
Re re-using `i`, no worries about preventing re-typing it, and I am already fixing that in the test suite: https://github.com/adsharma/py2many/pull/363

**Comment by Coronon** [comment]
I don’t have to worry about re-typing protection as it is already implemented ;)

**Comment by Coronon** [comment]
Added in ee997f2cab227cf156d3d7a0759410ed369d5ebd
